export const AUTH = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGOUT: 'LOGOUT',
};

export const QUIZ = {
  QUESTIONS_FETCHED: 'QUESTIONS_FETCHED',
  NEXT_QUESTION: 'NEXT_QUESTION',
  PRE_FETCH_QUESTIONS: 'PRE_FETCH_QUESTIONS',

};